// assets/index-DmX9vQ2s.js — Vite 7 / Rollup 4 production build
// Generated by vite build --mode production. Do not edit.
const __vite__mapDeps = (i, m = __vite__mapDeps, d = m.f || (m.f = [
  "assets/index-DmX9vQ2s.js",
  "assets/vendor-BkP2nQ4z.js",
  "assets/app-Cq7mR1Xt.css",
  "assets/checkout-Dn4rT8yV.js",
  "assets/profile-Bq9wL2mK.js"
])) => i.map((i) => d[i]);

const __vite__manifest = {
  "src/main.ts": {
    file: "assets/index-DmX9vQ2s.js",
    src: "src/main.ts",
    isEntry: true,
    integrity: "sha384-uIKNCLjLEeFjE/Kr7gbjFeuG2UGOH+IxcZ8I9amMmdT1O2T5XcFlXQn73+7pvPre",
    imports: ["_vendor-BkP2nQ4z.js"],
    css: ["assets/app-Cq7mR1Xt.css"],
    contentHash: "78ba480f4722ece43133b7485d2418279cc1321fac34f9700fa040248774299b"
  },
  "_vendor-BkP2nQ4z.js": {
    file: "assets/vendor-BkP2nQ4z.js",
    integrity: "sha384-LN1RP03SCXoPwWrOTYbxnnCIEFlmeilN30tjSLhU+rwpkWK/CaDuRuuCXGhrhR2H",
    contentHash: "6b535fcd83f5c1f0341151c92a9c074cddd217c1930fd7f2c02c380078c5afea"
  },
  "assets/app-Cq7mR1Xt.css": {
    file: "assets/app-Cq7mR1Xt.css",
    integrity: "sha384-tVWMuRkNJdpf5NzdN2MxtXzCnDH2X+6AiHA+f9tyLbZVlXHSdIdBJk8X6BOxzElW",
    contentHash: "9aedae52a4b35d9b24714cae5979748067eb2334a9b34049cb3bb884cc803615"
  }
};

const __vite__cacheTags = {
  etag: 'W/"8f0ebcd03824029dc8f19ac0ee67d5dbcea67604"',
  lastModified: "Sat, 20 Sep 2026 07:41:19 GMT",
  revision: "3ef0a9e796e291e76e5fa53f24a3e297101ec107",
  buildId: "d37fc76ca361f5ffe8f3f94623d326563efd69e9"
};

const scriptRel = "modulepreload";
const seen = {};

const __vitePreload = function (baseModule, deps, importerUrl) {
  if (!deps || deps.length === 0) return baseModule();
  const links = document.getElementsByTagName("link");
  return Promise.allSettled(
    deps.map((dep) => {
      dep = new URL(dep, importerUrl).href;
      if (dep in seen) return;
      seen[dep] = true;
      const isCss = dep.endsWith(".css");
      const cssSelector = isCss ? '[rel="stylesheet"]' : "";
      for (let i = links.length - 1; i >= 0; i--) {
        const link = links[i];
        if (link.href === dep && (!isCss || link.rel === "stylesheet")) return;
      }
      const link = document.createElement("link");
      link.rel = isCss ? "stylesheet" : scriptRel;
      if (!isCss) {
        link.as = "script";
        link.crossOrigin = "";
      }
      link.href = dep;
      const entry = Object.values(__vite__manifest).find((m) => dep.endsWith(m.file));
      if (entry && entry.integrity) link.integrity = entry.integrity;
      document.head.appendChild(link);
      if (isCss) {
        return new Promise((res, rej) => {
          link.addEventListener("load", res);
          link.addEventListener("error", () => rej(new Error(`css load failed: ${dep}`)));
        });
      }
    })
  ).then(() => baseModule());
};

const rollupImportMap = {
  imports: {
    "@acme/ui": "/assets/vendor-BkP2nQ4z.js",
    "@acme/icons": "/assets/icons-Dt3nV7wQ.js",
    "@acme/telemetry": "/assets/telemetry-Bx8kM4pL.js"
  },
  integrity: {
    "/assets/vendor-BkP2nQ4z.js": "sha384-LN1RP03SCXoPwWrOTYbxnnCIEFlmeilN30tjSLhU+rwpkWK/CaDuRuuCXGhrhR2H"
  }
};

export { __vite__mapDeps, __vite__manifest, __vite__cacheTags, __vitePreload, rollupImportMap };
//# sourceMappingURL=index-DmX9vQ2s.js.map
